import { useEffect, useMemo } from "react";
import { useDateStore } from "../../store/current_date.store";
import { getWeek } from "../../utils/functions/getFormatDate";

const WeeklySummary = () => {
  const { start_date, end_date } = useMemo(() => getWeek(), []);

  const setDate = useDateStore((state) => state.setDate);
  useEffect(() => {
    setDate(start_date, end_date);
  }, []);

  return (
    <div className="wr-header">
      <div className="wr-title">Customer Success — Weekly Summary</div>
      <div className="wr-period">
        {start_date.toDateString()} – {end_date.toDateString()} · Generated by
        RightMonitor
      </div>
      <div className="wr-kpis">
        <div className="wr-kpi">
          <div className="wr-kpi-val">%</div>
          <div className="wr-kpi-lbl">GRR</div>
          <div className="wr-kpi-trend">▲ +1.3% vs prev. week</div>
        </div>
        <div className="wr-kpi">
          <div className="wr-kpi-val">108.7%</div>
          <div className="wr-kpi-lbl">NRR</div>
          <div className="wr-kpi-trend">▲ +3.1% vs prev. week</div>
        </div>
        <div className="wr-kpi">
          <div className="wr-kpi-val">1.8%</div>
          <div className="wr-kpi-lbl">Logo Churn</div>
          <div className="wr-kpi-trend">▲ +0.4% — watch closely</div>
        </div>
        <div className="wr-kpi">
          <div className="wr-kpi-val">$142K</div>
          <div className="wr-kpi-lbl">Pipeline</div>
          <div className="wr-kpi-trend">4 active opportunities</div>
        </div>
      </div>
    </div>
  );
};

export default WeeklySummary;
